

 const List<String> getCategories = [
        "All",
        "Advertise",
        "Agriculture",
        "Airlines"
        "Automobile",
        "Banking",
        "Beauty/Fitness",
        "Bio Technology",
        "Cement",
        "Chemicals",
        "Construction",
        "Consultancy",
        "Consumer Goods",
        "Courier/Freight",
        "Dairy",
        "Education",
        "Electrical",
        "Engineering",
        "Entertainment",
        "Facility Management",
        "Fertilizer/Pesticides",
        "Financial Services",
        "Food & Packaged Food",
        "Government/Defence",
        "Health Care",
        "Home Appliances",
        "Hospitals",
        "Hotels/Restaurant",
        "Import/Export",
        "Insurance",
        "Iron/Steel",
        "IT Hardware",
        "IT Software",
        "IT Web Dev",
        "Gold/Jewellery",
        "Leather",
        "Machinery/Equipment",
        "Market Research",
        "Media",
        "Medical Equipments",
        "Office Equipment",
        "Paints",
        "Paper",
        "Personal Care/SPA",
        "Pharmaceuticals",
        "Plastic",
        "Printing/Packaging",
        "Public Relations",
        "Publishing",
        "Real Estate",
        "Retailing",
        "Rubber",
        "Shipping",
        "Telecom",
        "Textiles",
        "Transportation",
        "Travel/Tourism",
        "Tyres",
        "Wood",
        "Other"
   ];


const List<String> getCategoryValue = [
        "All",
        "Advertising",
        "Agriculture",
        "Airlines"
        "Automobile",
        "Banking",
        "Beauty/Fitness",
        "Bio Technology",
        "Cement",
        "Chemicals",
        "Construction",
        "Consultancy",
        "Consumer Goods",
        "Courier/Freight",
        "Dairy",
        "Education",
        "Electrical",
        "Engineering",
        "Entertainment",
        "Facility Management",
        "Fertilizer/Pesticides",
        "Financial Services",
        "Food & Packaged Food",
        "Government/Defence",
        "Health Care",
        "Home Appliances",
        "Hospitals",
        "Hotels/Restaurant",
        "Import/Export",
        "Insurance",
        "Iron/Steel",
        "IT/Computers - Hardware",
        "IT/Computers - Software",
        "IT/Computers - Web Development",
        "Gold/Jewellery",
        "Leather",
        "Machinery/Equipment Mfg.",
        "Market Research",
        "Media",
        "Medical Equipments Mfg.",
        "Office Equipment",
        "Paints",
        "Papers",
        "Personal Care/SPA",
        "Pharmaceuticals",
        "Plastic",
        "Printing/Packaging",
        "Public Relations",
        "Publishing",
        "Real Estate",
        "Retailing",
        "Rubber",
        "Shipping",
        "Telecom",
        "Textiles",
        "Transportation",
        "Travel/Tourism",
        "Tyres",
        "Wood",
        "Other"
   ];